# fly.toml app configuration file generated for zen-demo-python on 2025-03-18T20:32:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zen-demo-python-danger'
primary_region = 'ams'

[[vm]]
  memory = '1024mb'
  cpu_kind = 'performance'
  cpus = 1

[env]
AIKIDO_DISABLE = 'true'
